In [43]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from scipy.sparse.construct import random

from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

from sklearn.tree import export_graphviz
from six import StringIO
from IPython.display import Image  
import pydotplus

In [2]:
path = "/Users/ercongluo/Documents/GU/501/501portfolio/datasets/NewsData/"
DF = pd.read_csv(path + "NewsData_cleanedDF.csv")
DF

Unnamed: 0        source  \
0            0    TechCrunch   
1            1    TechCrunch   
2            2     Wiley.com   
3            3       Reuters   
4            4       Reuters   
..         ...           ...   
95          95  The Guardian   
96          96     Zacks.com   
97          97       Reuters   
98          98       Reuters   
99          99       Reuters   

                                                title  \
0   ev charging solutions become asset liability grid   
1   hyundai motor group unveils hydrogen strategy ...   
2   electric vehicles produce substantial toxicity...   
3   zurich insurance sets climate steps curb c02 e...   
4   update 1 zurich insurance sets climate steps c...   
..                                                ...   
95          deep sea mining cure climate crisis curse   
96  auto stock roundup aap xpev q2 results f outpu...   
97  illinois senate passes bill save nuclear plant...   
98  illinois senate passes bill save nuclear plant...   
99  update 1 illinois senate passes bill save nucl...   

                                          description  \
0   although wireless charging still relatively ne...   
1   hyundai motor group backing hydrogen top energ...   
2   electric vehicles evs coupled low carbon elect...   
3   zurich insurance group href https www reuters ...   
4   zurich insurance group unveiled new climate me...   
..                                                ...   
95  trillions metallic nodules sea floor could hel...   
96  advance auto parts aap xpeng xpev deliver impr...   
97  illinois senate passed bill early wednesday ai...   
98  illinois senate passed bill early wednesday ai...   
99  illinois senate passed bill early wednesday ai...   

                                              content  
0   president joe biden’s plan electric vehicles e...  
1   hyundai motor group backing hydrogen top energ...  
2   introduction global society dependent road tra...  
3   ceo mario greco swiss zurich insurance address...  
4   reuters staff file photo ceo mario greco swiss...  
..                                                ...  
95  display cabinet recently opened broken planet ...  
96  august 30 2021 5 min read story originally app...  
97  company law firm names shown generated automat...  
98  reuters illinois senate passed bill early wedn...  
99  adds exelon comment sept 1 reuters illinois se...  

[100 rows x 5 columns]

In [48]:
labels = [-1, -1, -1,  0,  0, -1,  1,  1, -1, -1,  2, -1, -1, -1, -1, -1,  3, -1, -1, -1, -1, -1, -1, -1,
 -1, -1, -1, -1, -1, -1, -1,  3, -1, -1, -1, -1,  4, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
 -1, -1, -1, -1,  1, -1, -1, -1, -1,  5,  2, -1,  4, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
 -1, -1, -1, -1, -1, -1, -1, -1,  6, -1, -1, -1, -1, -1, -1, -1, -1,  5, -1, -1, -1, -1, -1, -1,
 -1, -1,  6,  6]
for i in range(100):
    if labels[i] == 1 or labels[i] == -1: # relevant labels
        labels[i] = 1
    else: 
        labels[i] = 0 # irrelevant labels

In [9]:
DF['label'] = labels

In [22]:
vectorizer = TfidfVectorizer(stop_words = 'english')
X = vectorizer.fit_transform(DF['description'])

In [44]:
clf = DecisionTreeClassifier(criterion = "entropy", splitter = "best", max_depth = 3)

# Train Decision Tree Classifer
clf = clf.fit(X,labels)

#Predict the response for test dataset
y_pred = clf.predict(X)

train_acc = metrics.accuracy_score(labels, clf.predict(X))
print("Training accuracy:", train_acc)

dot_data = export_graphviz(clf,
                        out_file = None,
                        feature_names = list(vectorizer.vocabulary_.keys()),
                        class_names = ['0','1'],
                        filled = True,
                        rounded = True,
                        special_characters = True)
graph = pydotplus.graph_from_dot_data(dot_data)  
graph.write_png('text_DT1.png')
Image(graph.create_png())
print(confusion_matrix(labels, y_pred))

Training accuracy: 0.95
[[ 8  5]
 [ 0 87]]


In [45]:
clf = DecisionTreeClassifier(criterion = "entropy", splitter = "best", max_depth = 5)

# Train Decision Tree Classifer
clf = clf.fit(X,labels)

#Predict the response for test dataset
y_pred = clf.predict(X)

train_acc = metrics.accuracy_score(labels, clf.predict(X))
print("Training accuracy:", train_acc)

dot_data = export_graphviz(clf,
                        out_file = None,
                        feature_names = list(vectorizer.vocabulary_.keys()),
                        class_names = ['0','1'],
                        filled = True,
                        rounded = True,
                        special_characters = True)
graph = pydotplus.graph_from_dot_data(dot_data)  
graph.write_png('text_DT2.png')
Image(graph.create_png())
print(confusion_matrix(labels, y_pred))

Training accuracy: 0.98
[[13  0]
 [ 2 85]]


In [49]:
clf = DecisionTreeClassifier(criterion = "gini", splitter = "best", max_depth = 10)

# Train Decision Tree Classifer
clf = clf.fit(X,labels)

#Predict the response for test dataset
y_pred = clf.predict(X)

train_acc = metrics.accuracy_score(labels, clf.predict(X))
print("Training accuracy:", train_acc)

dot_data = export_graphviz(clf,
                        out_file = None,
                        feature_names = list(vectorizer.vocabulary_.keys()),
                        class_names = ['0','1'],
                        filled = True,
                        rounded = True,
                        special_characters = True)
graph = pydotplus.graph_from_dot_data(dot_data)  
graph.write_png('text_DT3.png')
Image(graph.create_png())
print(confusion_matrix(labels, y_pred))

Training accuracy: 0.98
[[13  0]
 [ 2 85]]
